services:
  postgres:
    image: postgres:17.5
    container_name: ${APP_NAME:-nestapp}_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-neokanban}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      - backend
    
  mongodb:
    image: mongo:noble
    container_name: ${APP_NAME:-nestapp}_mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB:-neokanban}
    volumes:
      - ./data/mongodb:/data/db
    ports:
      - "${MONGO_PORT:-27017}:27017"
    networks:
      - backend

networks:
  backend:
    driver: bridge
    name: ${APP_NAME:-nestapp}_network